### ISSUE TITLE
Java 8 issue

### ISSUE THREAD

**Issue by xpavlic4** [AtomicScala/atomic-scala-examples#4]
Activator team wrote me: 

The Atomic Scala template uses a Scala version that unfortunately does not support Java8.
See: http://stackoverflow.com/questions/24517761/scala-repl-throws-error

There are a couple of ways around this.

run the existing template with a Java version < 8 (e.g. 6 or 7).
keep Java8 as JVM runtime and instead change the Scala version in the template (change all 2.10.1 to 2.10.4 in the file build.sbt)

**Comment by BruceEckel** [comment]
This should be corrected now. If you have any more problems please re-post another issue. Thanks!
